spring:
  application:
    name: bike-back
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    redis:
      repositories:
        enabled: false

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET}
    issuer: ${AUTH_JWT_ISSUER:bike-back}
    token-validity-sec: ${AUTH_JWT_TOKEN_VALIDITY_SEC:86400}
