spring:
  application:
    name: bike-back
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    redis:
      repositories:
        enabled: false
