graphhopper:
  datareader.file: ""
  graph.location: /data/graph-cache

  profiles:
    - name: bike
      custom_model_files: [bike_project_bike.json, bike_project_elevation.json]

  profiles_ch: []
  profiles_lm: []

  graph.encoded_values: |
    road_class, road_environment, surface, smoothness,
    bike_access, backward_bike_access, bike_average_speed, bike_priority, bike_road_access, bike_network,
    foot_road_access, roundabout, mtb_rating, ferry_speed, hike_rating, country, average_slope, max_slope

  graph.elevation.provider: srtm
  graph.elevation.cache_dir: /data/srtm-cache
  graph.elevation.interpolate: bilinear

  routing.non_ch.max_waypoint_distance: 1000000
  import.osm.ignored_highways: ''

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
