ALTER TABLE user_consents
    ADD COLUMN IF NOT EXISTS age_verified BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS age_band VARCHAR(20) NOT NULL DEFAULT 'ADULT',
    ADD COLUMN IF NOT EXISTS age_verified_at TIMESTAMPTZ NOT NULL DEFAULT now();
